### ISSUE TITLE
Subscription should be done with using POST?

### ISSUE THREAD

**Issue by aalvrz** [victoriadrake/simple-subscribe#1]
First of all great tutorial and project! I am learning Go and found this extremely useful. I could not find a place to leave comments in your blog post or on FreeCodeCamp, so I decided to try here. 

I saw that the initial subscribe request to API Gateway is done using a HTML form and a GET Request. By convention, shouldn't this be done using a POST request? I decided to give this a try but it turned out to be more complicated than I thought. Submitting the form using POST sends a `multipart/form-data` request, but I am finding impossible parsing this using Go in the lambda handler. The data is correctly found in the request's `Body`, but I have no idea how to retrieve it from there. It is not as straightforward as using `QueryStringParameters["email"]` or decoding with JSON if the data was `application/json`.

I can't find any examples to achieve this. Would appreciate some help if you have time.

**Comment by victoriadrake** [comment]
Hello Andrés! Thanks for this great question!

From a REST API design perspective, you're right that it's conventionally a POST. As you mentioned, the downside is that it adds additional complexity to handle a POST request. 

For a small project like this, one advantage of using GET is that it makes it trivial to interact with the API using a browser. Sending data in a querystring is as easy as clicking once on a link, which is especially nice for the confirmation and unsubscribe steps.

To use POST instead, I'd be using a tool like `curl` while developing, and I'd also need to create form pages on my website so that users can interact with the confirmation and unsubscribe functions. For the user, this turns a one-step task into a three-step task (click link in email, load form page in browser, submit form), and this appeals to me less.

For working with a `multipart/form-data` request, you might want to look at some of the methods in `http` such as [`MultipartReader`](https://golang.org/pkg/net/http/#Request.MultipartReader) or [`ParseForm`](https://golang.org/pkg/net/http/#Request.ParseForm). I hope that helps!
